### ISSUE TITLE
expect should stop waiting when child process exits

### ISSUE THREAD

**Issue by rampion** [wuest/expectr#4]
If the child process exits, then `expect` should exit immediately.

Currently my work-around is to have the child process kill its parent:

```ruby
Signal.trap("TERM") { exit 0 }
exp = Expectr.new(
  ARGV.map(&:inspect).join(' ') + " ; kill -TERM #{ Process.pid }",
  :timeout => 0
)
while exp.expect( "? " ) do
  exp.send "yes"
end
```

Without that explicit killing, I'm stuck waiting on a `Timeout` error from expect.

**Comment by wuest** [comment]
Hi there!  I'm so sorry for letting this sit for so long.

The above patch should (mostly) address your issue.  It is expected that you can create multiple Expectr objects, so exiting outright when one process exits wouldn't fit the goals of the project.  To achieve what you want, it would look something like this:

```ruby
exp = Expectr.new(ARGV.map(&:inspect).join(' '), :timeout => 0)
begin
  exp.puts 'yes' while exp.expect('? ')
rescue Timeout::Error
  exit 0 # Exit without backtrace
end
```

**Comment by rampion** [comment]
Sorry, I didn't mean that the process running `Expectr#expect` should exit, I mean that `Expect#expect` should return something falsy when the child process exits.

I tried the update but it doesn't quite seem to be working, as it raises a fatal exception on my machine:

    % gem list expectr
    expectr (2.0.1)
    % cat my-yes.rb
    require 'expectr'
    require 'expectr'
    exp = Expectr.new(ARGV.map(&:inspect).join(' '), :timeout => 0)
    exp.puts 'yes' while exp.expect('? ', true)
    % cat cheese.rb
    3.times do
      print "Do you you like cheese? "
      gets
    end
    % ruby my-yes.rb ruby cheese.rb
    Do you you like cheese? yes
    Do you you like cheese? yes
    Do you you like cheese? yes
    /usr/local/rvm/gems/ruby-2.1.5/gems/expectr-2.0.1/lib/expectr.rb:320:in `sleep': No live threads left. Deadlock? (fatal)
      from /usr/local/rvm/gems/ruby-2.1.5/gems/expectr-2.0.1/lib/expectr.rb:320:in `block in check_match'
      from /usr/local/rvm/gems/ruby-2.1.5/gems/expectr-2.0.1/lib/expectr.rb:318:in `synchronize'
      from /usr/local/rvm/gems/ruby-2.1.5/gems/expectr-2.0.1/lib/expectr.rb:318:in `check_match'
      from /usr/local/rvm/gems/ruby-2.1.5/gems/expectr-2.0.1/lib/expectr.rb:341:in `block in watch_match'
      from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
      from /usr/local/rvm/gems/ruby-2.1.5/gems/expectr-2.0.1/lib/expectr.rb:340:in `watch_match'
      from /usr/local/rvm/gems/ruby-2.1.5/gems/expectr-2.0.1/lib/expectr.rb:186:in `expect'
      from my-yes.rb:3:in `<main>'

**Comment by wuest** [comment]
Hi there,

f03f7358d9b8c9170980efc1b8c4ed938c04b5fa fixes the crash you're experiencing, so I'm relatively certain that you aren't actually using the patch  The two ways you can ensure you're using the patch are:
* Invoke ruby with e.g. `ruby -Ilib my-yes.rb ruby cheese.rb` (from within the Expectr repo dir assuming it's synced with the issue_4 branch)
* Build and install the gem prior to running the test.  As of 93340be38980d097d0d23e5066484540e44dd44b I've bumped the version to 2.0.2.pre.a so you can be sure you're using the version which addresses your issue.

**Comment by rampion** [comment]
I think I am, but I'm still seeing the bug:

    % git checkout 93340be
    HEAD is now at 93340be... Bump version (pre-release)
    % ruby -Ilib my-yes.rb ruby cheese.rb
    expectr-2.0.2-a
    Do you you like cheese? yes
    Do you you like cheese? yes
    Do you you like cheese? yes
    /Users/rampion/Projects/expectr/lib/expectr.rb:322:in `sleep': No live threads left. Deadlock? (fatal)
            from /Users/rampion/Projects/expectr/lib/expectr.rb:322:in `block in check_match'
            from /Users/rampion/Projects/expectr/lib/expectr.rb:318:in `synchronize'
            from /Users/rampion/Projects/expectr/lib/expectr.rb:318:in `check_match'
            from /Users/rampion/Projects/expectr/lib/expectr.rb:344:in `block in watch_match'
            from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
            from /Users/rampion/Projects/expectr/lib/expectr.rb:343:in `watch_match'
            from /Users/rampion/Projects/expectr/lib/expectr.rb:186:in `expect'
            from my-yes.rb:4:in `<main>'
    % cat my-yes.rb 
    require 'expectr'
    puts "expectr-#{Expectr::VERSION}"
    exp = Expectr.new(ARGV.map(&:inspect).join(' '), :timeout => 0)
    exp.puts 'yes' while exp.expect('? ', true)

I build and installed 2.0.2-a and saw the same behaviour.

    % gem build expectr.gemspec
      Successfully built RubyGem
      Name: expectr
      Version: 2.0.2.pre.a
      File: expectr-2.0.2.pre.a.gem
    % gem install expectr-2.0.2.pre.a.gem
    Successfully installed expectr-2.0.2.pre.a
    Parsing documentation for expectr-2.0.2.pre.a
    Installing ri documentation for expectr-2.0.2.pre.a
    Done installing documentation for expectr after 0 seconds
    1 gem installed
    % ruby my-yes.rb ruby cheese.rb
    expectr-2.0.2-a
    Do you you like cheese? yes
    Do you you like cheese? yes
    Do you you like cheese? yes
    /usr/local/rvm/gems/ruby-2.1.5/gems/expectr-2.0.2.pre.a/lib/expectr.rb:322:in `sleep': No live threads left. Deadlock? (fatal)
            from /usr/local/rvm/gems/ruby-2.1.5/gems/expectr-2.0.2.pre.a/lib/expectr.rb:322:in `block in check_match'
            from /usr/local/rvm/gems/ruby-2.1.5/gems/expectr-2.0.2.pre.a/lib/expectr.rb:318:in `synchronize'
            from /usr/local/rvm/gems/ruby-2.1.5/gems/expectr-2.0.2.pre.a/lib/expectr.rb:318:in `check_match'
            from /usr/local/rvm/gems/ruby-2.1.5/gems/expectr-2.0.2.pre.a/lib/expectr.rb:344:in `block in watch_match'
            from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
            from /usr/local/rvm/gems/ruby-2.1.5/gems/expectr-2.0.2.pre.a/lib/expectr.rb:343:in `watch_match'
            from /usr/local/rvm/gems/ruby-2.1.5/gems/expectr-2.0.2.pre.a/lib/expectr.rb:186:in `expect'
            from my-yes.rb:4:in `<main>'

**Comment by wuest** [comment]
Weird!  I'll look into this more; I'm unable to replicate the behavior on 2.2 or 2.1.

Expect an update by this evening.

**Comment by wuest** [comment]
I haven't been able to replicate the race condition you're encountering.  However, I believe that e8e86f0d2cd6082fc0d8e6f9971268e29950d9be should fix it, given what you're seeing.

**Comment by rampion** [comment]
I was able to capture all the thread activity and it looks like `@stdout.sysread(@buffer_size, buf)` raises `EOFError` on my system, which was happening while the
`@out_mutex` was sleeping, causing the error:


    % cat my-yes.rb
    require 'expectr'

    puts "expectr-#{Expectr::VERSION}"

    threads = Hash.new { |h,k| h[k] = h.length }
    thread_id = lambda { threads[ Thread.current.object_id ] }

    [ Expectr, Expectr::Child ].each do |klass|
      klass.class_eval do
        public *private_instance_methods(false)
        instance_methods(false).each do |meth_name|
          STDERR.puts "wrapping #{klass}##{meth_name}"
          original_method = instance_method(meth_name)
          define_method(meth_name) do |*args,&blk|
            STDERR.puts "\e[#{31+thread_id[]}m#{thread_id[]}: <#{klass}##{meth_name}>\e[m"
            begin
              rv = original_method.bind(self).call(*args,&blk)
            rescue Exception => e
              STDERR.puts "\e[#{31+thread_id[]}m#{thread_id[]}: #{e.inspect}\e[m"
              raise
            ensure
              STDERR.puts "\e[#{31+thread_id[]}m#{thread_id[]}: </#{klass}##{meth_name}>\e[m"
            end
            rv
          end
        end
      end
    end

    exp = Expectr.new(ARGV.map(&:inspect).join(' '), :timeout => 0)
    exp.puts 'yes' while exp.expect('? ', true)
    % ruby -Ilib my-yes.rb ruby cheese.rb
    expectr-2.0.2-a
    wrapping Expectr#timeout
    wrapping Expectr#timeout=
    wrapping Expectr#flush_buffer
    wrapping Expectr#flush_buffer=
    wrapping Expectr#buffer_size
    wrapping Expectr#buffer_size=
    wrapping Expectr#constrain
    wrapping Expectr#constrain=
    wrapping Expectr#pid
    wrapping Expectr#buffer
    wrapping Expectr#discard
    wrapping Expectr#initialize
    wrapping Expectr#interact!
    wrapping Expectr#interact?
    wrapping Expectr#leave!
    wrapping Expectr#puts
    wrapping Expectr#expect
    wrapping Expectr#expect_procmap
    wrapping Expectr#clear_buffer!
    wrapping Expectr#print_buffer
    wrapping Expectr#force_utf8
    wrapping Expectr#parse_options
    wrapping Expectr#setup_instance
    wrapping Expectr#process_output
    wrapping Expectr#check_match
    wrapping Expectr#watch_match
    wrapping Expectr#process_procmap
    wrapping Expectr::Child#init_interface
    wrapping Expectr::Child#kill!
    wrapping Expectr::Child#send
    wrapping Expectr::Child#output_loop
    wrapping Expectr::Child#winsize
    wrapping Expectr::Child#prepare_interact_environment
    wrapping Expectr::Child#interact_thread
    0: <Expectr#initialize>
    0: <Expectr#setup_instance>
    0: </Expectr#setup_instance>
    0: <Expectr#parse_options>
    0: </Expectr#parse_options>
    0: <Expectr::Child#init_interface>
    0: </Expectr::Child#init_interface>
    0: </Expectr#initialize>
    1: <Expectr::Child#output_loop>
    0: <Expectr#expect>
    0: <Expectr#watch_match>
    0: <Expectr#check_match>
    1: <Expectr#process_output>
    1: <Expectr#force_utf8>
    1: </Expectr#force_utf8>
    1: <Expectr#print_buffer>
    Do you you like cheese? 1: </Expectr#print_buffer>
    1: </Expectr#process_output>
    0: </Expectr#check_match>
    0: </Expectr#watch_match>
    0: </Expectr#expect>
    0: <Expectr#puts>
    0: <Expectr::Child#send>
    1: <Expectr#process_output>
    1: <Expectr#force_utf8>
    1: </Expectr#force_utf8>
    1: <Expectr#print_buffer>
    yes
    Do you you like cheese? 1: </Expectr#print_buffer>
    1: </Expectr#process_output>
    0: </Expectr::Child#send>
    0: </Expectr#puts>
    0: <Expectr#expect>
    0: <Expectr#watch_match>
    0: <Expectr#check_match>
    0: </Expectr#check_match>
    0: </Expectr#watch_match>
    0: </Expectr#expect>
    0: <Expectr#puts>
    0: <Expectr::Child#send>
    0: </Expectr::Child#send>
    0: </Expectr#puts>
    0: <Expectr#expect>
    0: <Expectr#watch_match>
    0: <Expectr#check_match>
    1: <Expectr#process_output>
    1: <Expectr#force_utf8>
    1: </Expectr#force_utf8>
    1: <Expectr#print_buffer>
    yes
    Do you you like cheese? 1: </Expectr#print_buffer>
    1: </Expectr#process_output>0: </Expectr#check_match>
    0: </Expectr#watch_match>
    0: </Expectr#expect>
    0: <Expectr#puts>
    0: <Expectr::Child#send>

    0: </Expectr::Child#send>
    0: </Expectr#puts>
    0: <Expectr#expect>
    0: <Expectr#watch_match>
    0: <Expectr#check_match>
    1: <Expectr#process_output>
    1: <Expectr#force_utf8>
    1: </Expectr#force_utf8>
    1: <Expectr#print_buffer>
    yes
    1: </Expectr#print_buffer>
    1: </Expectr#process_output>
    1: #<EOFError: end of file reached>
    1: </Expectr::Child#output_loop>
    0: #<fatal: No live threads left. Deadlock?>
    0: </Expectr#check_match>
    0: #<fatal: No live threads left. Deadlock?>
    0: </Expectr#watch_match>
    0: #<fatal: No live threads left. Deadlock?>
    0: </Expectr#expect>
    /Users/rampion/Projects/expectr/lib/expectr.rb:322:in `sleep': No live threads left. Deadlock? (fatal)
            from /Users/rampion/Projects/expectr/lib/expectr.rb:322:in `block in check_match'
            from /Users/rampion/Projects/expectr/lib/expectr.rb:318:in `synchronize'
            from /Users/rampion/Projects/expectr/lib/expectr.rb:318:in `check_match'
            from my-yes.rb:17:in `call'
            from my-yes.rb:17:in `block (4 levels) in <main>'
            from /Users/rampion/Projects/expectr/lib/expectr.rb:344:in `block in watch_match'
            from /usr/local/rvm/rubies/ruby-2.1.5/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
            from /Users/rampion/Projects/expectr/lib/expectr.rb:343:in `watch_match'
            from my-yes.rb:17:in `call'
            from my-yes.rb:17:in `block (4 levels) in <main>'
            from /Users/rampion/Projects/expectr/lib/expectr.rb:186:in `expect'
            from my-yes.rb:17:in `call'
            from my-yes.rb:17:in `block (4 levels) in <main>'
            from my-yes.rb:31:in `<main>'

I tried e8e86f0 and while that avoided the error, it caused the program to hang.

A fix that worked on my system was simply to add `EOFError` to the list of errors that can signal the end of the child process:

    begin
      @stdout.sysread(@buffer_size, buf)
    rescue Errno::EIO, EOFError #Application is not running
      @pid = 0
      @thread.wakeup if @thread
      return
    end

**Comment by wuest** [comment]
Thank you for tracking this down!  f9c803c2950889a79c6c450cd144fc7c84455171 integrates your fix and removes my shot in the dark from e8e86f0d2cd6082fc0d8e6f9971268e29950d9be.  If you don't mind verifying that everything's kosher, I'll be cutting a new gem after hearing back from you.

**Comment by wuest** [comment]
By the by, do you mind if I thank you publicly?  I realize your twitter isn't linked via your github page.

**Comment by rampion** [comment]
Hunh, guess I should do that. 

No I don't mind. Thank you!
